backend:
  name: github
  branch: main
  repo: cunzhong/Twilight # 请替换为您的 GitHub 仓库
  site_domain: tw.088878.xyz # 请替换为您的域名
  base_url: https://tw.088878.xyz  # 请替换为您的 URL
  auth_endpoint: oauth # OAuth 路由由集成提供

# 媒体文件配置
media_folder: "public/images" # 媒体文件存储路径
public_folder: "/images" # 公共访问路径

# 集合配置
collections:
  # 博客文章集合
  - name: "posts"
    label: "Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Published Date", name: "published", widget: "datetime"}
      - {label: "Updated Date", name: "updated", widget: "datetime", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", default: [], required: false}
      - {label: "Category", name: "category", widget: "string", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}

# 编辑器配置
editor:
  preview: true  # 启用预览功能